apiVersion: v1
kind: Service
metadata:
  name: prescription-service
  labels:
    app: prescription-service
spec:
  selector:
    app: prescription-ms
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3001
#      nodePort: 31110